apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: dev
  namespace: observability
spec:
  config:
    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"

    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      jaeger:
        protocols:
          thrift_binary: {}
          thrift_compact: {}
          thrift_http: {}
          grpc: {}

    processors:

    exporters:
      debug: {}
      otlp:
        endpoint: "tempo-simplest-gateway.observability.svc:4317"
        tls:
          insecure: true
        auth:
          authenticator: bearertokenauth

    service:
      extensions: [bearertokenauth]
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          exporters: [otlp, debug]

