apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: dev
  namespace: observability
spec:
  config:
    #extensions:
    #  bearertokenauth:
    #    filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"

    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      jaeger:
        protocols:
          thrift_binary: {}
          thrift_compact: {}
          thrift_http: {}
          grpc: {}

    processors:

    exporters:
      debug: {}
      otlp:
        endpoint: "tempo-simplest-distributor.observability.svc:4317"
        
        tls:
          insecure_skip_verify: true 
          
        #auth:
        #  authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: "dev"

    service:
      #extensions: [bearertokenauth]
      extensions: []
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          exporters: [otlp, debug]

