- name: Verificar si el realm ya existe
  uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}"
    method: GET
    headers:
      Authorization: "Bearer {{ kc_token }}"
    return_content: false
    status_code: [200, 404]
    validate_certs: false
  register: realm_exists

- name: Importar realm
  when: realm_exists.status == 404
  uri:
    url: "https://{{ keycloak_hostname }}/admin/realms"
    method: POST
    headers:
      Authorization: "Bearer {{ kc_token }}"
    body: "{{ lookup('file', realm_json_path) | from_json }}"
    body_format: json
    status_code: 201
    validate_certs: false