- name: Ensure namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ rhdh_namespace }}"
    state: present

- name: Ensure namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ gitlab_namespace }}"
    state: present

- name: Crear Secret keycloak-client-secret en OpenShift
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: keycloak-client-secret
        namespace: "{{ rhdh_namespace }}"
      type: Opaque
      stringData:
        clientSecret: "{{ backstage_client_secret }}"

- name: Crear Secret gitlab-client-secret en OpenShift
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-client-secret
        namespace: "{{ gitlab_namespace }}"
      type: Opaque
      stringData:
        clientId: gitlab
        clientSecret: "{{ gitlab_client_secret }}"

- name: Crear Secret para configuración OIDC
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-oidc-config
        namespace: "{{ gitlab_namespace }}"
      type: Opaque
      stringData:
        omniauth.providers: |
          - name: 'openid_connect'
            label: 'Login with Keycloak'
            args:
              name: 'keycloak'
              scope: ['openid', 'profile', 'email', 'groups']
              response_type: 'code'
              issuer: '{{ keycloak_issuer_url }}'
              client_auth_method: 'query'
              redirect_uri: '{{ gitlab_base_url }}/users/auth/openid_connect/callback'
              authorization_endpoint: '{{ keycloak_authorization_endpoint }}'
              token_endpoint: '{{ keycloak_token_endpoint }}'
              userinfo_endpoint: '{{ keycloak_userinfo_endpoint }}'
              jwks_uri: '{{ keycloak_jwks_uri }}'
              client_id: '{{ keycloak_gitlab_client_id }}'
              client_secret: '{{ gitlab_client_secret }}'
              discovery: false
            block_auto_created_users: false
            auto_link_user: true
            sync_profile_from_provider: true
            sync_attributes: ['email', 'name', 'first_name', 'last_name']
            groups_attribute: 'groups'
            sync_groups_from_provider: true
            sync_time: 3600
            external_groups:
              - name: rhdh