- name: Regenerar client secret - Obtener info cliente
  uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/clients?clientId={{ keycloak_client_id }}"
    method: GET
    headers:
      Authorization: "Bearer {{ kc_token }}"
    validate_certs: false
  register: client_info

- name: Verificar que el cliente existe
  fail:
    msg: "No se encontró el cliente con clientId={{ keycloak_client_id }}"
  when: client_info.json is not defined or client_info.json | length == 0

- set_fact:
    client_id_internal: "{{ client_info.json[0].id }}"

- name: Regenerar client secret
  uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/clients/{{ client_id_internal }}/client-secret"
    method: POST
    headers:
      Authorization: "Bearer {{ kc_token }}"
    status_code: 200
    return_content: true
    validate_certs: false
  register: client_secret_response

- set_fact:
    backstage_client_secret: "{{ client_secret_response.json.value }}"