- name: Crear usuarios en Keycloak
  ansible.builtin.uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/users"
    method: POST
    headers:
      Authorization: "Bearer {{ kc_token }}"
      Content-Type: "application/json"
    body: |
      {
        "username": "{{ item.username }}",
        "enabled": true,
        "email": "{{ item.email }}",
        "emailVerified": true,
        "firstName": "{{ item.first_name }}",
        "lastName": "{{ item.last_name }}",
        "credentials": [{
          "type": "password",
          "value": "{{ item.password }}",
          "temporary": false
        }]
      }
    body_format: json
    status_code: [201, 409]
    validate_certs: false
  loop: "{{ user_list }}"
  loop_control:
    loop_var: item

- name: Obtener ID de usuarios recién creados
  ansible.builtin.uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/users?username={{ item.username }}"
    method: GET
    headers:
      Authorization: "Bearer {{ kc_token }}"
      Content-Type: "application/json"
    return_content: true
    validate_certs: false
    status_code: [200]
  register: user_lookup_result
  until: user_lookup_result.status == 200
  retries: 5
  delay: 5
  loop: "{{ user_list }}"
  loop_control:
    loop_var: item

- name: Obtener ID del grupo {{ group_name }}
  ansible.builtin.uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/groups"
    method: GET
    headers:
      Authorization: "Bearer {{ kc_token }}"
      Content-Type: "application/json"
    return_content: true
    validate_certs: false
    status_code: 200
  register: groups_result
  retries: 5
  delay: 10
  until: groups_result.status == 200
  
- name: Setear ID del grupo
  ansible.builtin.set_fact:
    current_group_id: >-
      {{
        (groups_result.json | selectattr('name', 'equalto', group_name) | list)[0].id
      }}

- name: Asociar usuarios al grupo {{ group_name }}
  ansible.builtin.uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/users/{{ item.1[0].id }}/groups/{{ current_group_id }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ kc_token }}"
      Content-Type: "application/json"
    status_code: 204
    validate_certs: false
  loop: "{{ user_list | zip(user_lookup_result.results | map(attribute='json') | list) | list }}"
  loop_control:
    loop_var: item