apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
spec:
  application:
    extraEnvs:
      secrets:
        - name: backstage-env
    extraFiles:
      mountPath: /opt/app-root/src
      configMaps:
        - name: rbac-policies
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: developer-hub-config
    replicas: 1
    #deploymentStrategy:
    #  type: Recreate
    route:
      enabled: true
  database:
    enableLocalDb: true
