apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak
  namespace: keycloak
spec:
  channel: stable-v26.2
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic